name: microgrid_sim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - jupyterlab
  - openpyxl
  - pip
  - requests
  - pvlib
  - python-dotenv
  - streamlit
  - plotly
  - pip:
    - nrel-nsrdb